apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan20-network
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "ext200-vlan",
      "type": "vlan",
      "master": "enp0s9",
      "vlanId": 20,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.200.0/24",
        "rangeStart": "192.168.200.101",
        "rangeEnd": "192.168.200.110",
        "gateway": "192.168.200.1"
      }
    }'
