apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: web-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # Multus 네트워크 적용
        k8s.v1.cni.cncf.io/networks: external-net
    spec:
      # worker1과 worker2에 하나씩 배치 (Node Affinity)
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
